import { LabelCount, OrganisationCount, ProjectsStats, SamplesStats, UsersStats } from "../../../domain/entities/stats";

// DB-derived part of `totals` (everything except storage size, which needs the filesystem,
// and except the derived task aggregates, which are computed in the repository).
export interface StatsTotalsDbPart {
    users: UsersStats;
    projects: ProjectsStats;
    samples: SamplesStats;
    tasks: {
        by_type: LabelCount[];
        by_status: LabelCount[];
    };
    top_organisations: OrganisationCount[];
}

// DB-derived scalars/breakdowns for the selected window.
export interface StatsPeriodScalarsDbPart {
    new_users: number;
    new_projects: number;
    new_samples: number;
    baseline_projects: number;     // created strictly before `from`
    baseline_samples: number;
    tasks_by_type: LabelCount[];
    tasks_by_status: LabelCount[];
}

// One row of the creation series: the interval key (generated by SQLite so it matches
// strftime exactly) with the number of projects/samples created in that interval.
export interface StatsCreationSeriesRow {
    label: string;
    projects: number;
    samples: number;
}

// A project row used for filesystem size attribution. `interval_label` is the strftime bucket
// key of the project's creation date (null when the project was created outside [from, to]);
// `is_baseline` marks projects created strictly before `from`.
export interface ProjectSizingRow {
    project_id: number;
    root_folder_path: string;
    is_baseline: boolean;
    interval_label: string | null;
}

export interface StatsDataSource {
    getTotals(): Promise<StatsTotalsDbPart>;
    getEarliestActivityDate(): Promise<string | null>;
    getPeriodScalars(from: string, to: string): Promise<StatsPeriodScalarsDbPart>;
    getCreationSeries(from: string, to: string, sqliteFormat: string): Promise<StatsCreationSeriesRow[]>;
    getProjectsForSizing(from: string, to: string, sqliteFormat: string): Promise<ProjectSizingRow[]>;
}
