services:
  api:
    image: 'ecotaxa/ecopart_back:latest'
    env_file: .env
    volumes:
      - ./data_storage:/src/data_storage
      - type: bind
        source: ./.env
        target: /src/.env
    ports:
      - 4000:4000
    restart: unless-stopped
    command: npm run prod:serve
