import { PublicSampleModel } from "../../src/domain/entities/sample";
import { SearchInfo } from "../../src/domain/entities/search";

export const sampleModel_1: PublicSampleModel = {
    sample_id: 1,
    sample_name: "perle3_001",
    comment: "no",
    instrument_serial_number: "205",
    optional_structure_id: "0",
    max_pressure: 1331,
    station_id: "A01",
    sampling_date: "20200313004656",
    latitude: 42.52702,
    longitude: 9.35195,
    wind_direction: 0,
    wind_speed: 0,
    sea_state: "0",
    nebulousness: 99,
    bottom_depth: 410,
    instrument_operator_email: "pierret@obs-vlfr.fr",
    filename: "20200313004656",
    sample_creation_date: "2024-11-20 16:35:31",
    filter_first_image: "2790",
    filter_last_image: "15872",
    instrument_settings_acq_gain: 200,
    instrument_settings_acq_description: "uvp5hd sn205 : mixtfd",
    instrument_settings_acq_task_type: 2,
    instrument_settings_acq_choice: 0,
    instrument_settings_acq_disk_type: 0,
    instrument_settings_acq_appendices_ratio: 3,
    instrument_settings_acq_xsize: 2048,
    instrument_settings_acq_ysize: 2048,
    instrument_settings_acq_erase_border: 0,
    instrument_settings_acq_threshold: 3,
    instrument_settings_process_datetime: "20200313004656",
    instrument_settings_process_gamma: 1,
    instrument_settings_images_post_process: "zooprocess",
    instrument_settings_aa: 0.003,
    instrument_settings_exp: 1.1976,
    instrument_settings_image_volume_l: 1.12,
    instrument_settings_pixel_size_mm: 0.092,
    instrument_settings_depth_offset_m: 6,
    instrument_settings_particle_minimum_size_pixels: 2,
    instrument_settings_vignettes_minimum_size_pixels: 80,
    instrument_settings_particle_minimum_size_esd: 0.25,
    instrument_settings_vignettes_minimum_size_esd: 0.25,
    instrument_settings_acq_shutter: 0,
    instrument_settings_acq_shutter_speed: 0,
    instrument_settings_acq_exposure: 0,
    visual_qc_validator_user_id: 1,
    visual_qc_validator_user: "undefined undefined (julie.coustenoble@imev-mer.fr)",
    visual_qc_status_id: 1,
    visual_qc_status_label: "PENDING",
    sample_type_id: 2,
    sample_type_label: "Depth",
    project_id: 5
}
export const sampleModel_2: PublicSampleModel =
{
    sample_id: 2,
    sample_name: "Mooring_0N_23W_201910_850m",
    comment: "0",
    instrument_serial_number: "000002LP",
    optional_structure_id: "0",
    max_pressure: 863.99,
    station_id: "0N_23W_830m",
    sampling_date: "20191012-151516",
    latitude: 0,
    longitude: -23,
    wind_direction: 90,
    wind_speed: 100,
    sea_state: "nan",
    nebulousness: 0,
    bottom_depth: 100,
    instrument_operator_email: "picheral@obs-vlfr.fr",
    filename: "20191012-000000_Merged-020",
    sample_creation_date: "2024-11-20 16:40:38",
    filter_first_image: "3432",
    filter_last_image: "107843",
    instrument_settings_acq_gain: 6,
    instrument_settings_acq_description: "uvp5hd sn000002LP : mixtfd",
    instrument_settings_acq_task_type: 2,
    instrument_settings_acq_choice: 0,
    instrument_settings_acq_disk_type: 0,
    instrument_settings_acq_appendices_ratio: 2,
    instrument_settings_acq_xsize: 2048,
    instrument_settings_acq_ysize: 2048,
    instrument_settings_acq_erase_border: 0,
    instrument_settings_acq_threshold: 23,
    instrument_settings_process_datetime: "20191012-151516",
    instrument_settings_process_gamma: 1,
    instrument_settings_images_post_process: "uvpapp",
    instrument_settings_aa: 1130,
    instrument_settings_exp: 1.313,
    instrument_settings_image_volume_l: 0.63,
    instrument_settings_pixel_size_mm: 73,
    instrument_settings_depth_offset_m: 999,
    instrument_settings_particle_minimum_size_pixels: 2,
    instrument_settings_vignettes_minimum_size_pixels: 80,
    instrument_settings_particle_minimum_size_esd: 700,
    instrument_settings_vignettes_minimum_size_esd: 700,
    instrument_settings_acq_shutter: 10,
    instrument_settings_acq_shutter_speed: 10,
    instrument_settings_acq_exposure: 0,
    visual_qc_validator_user_id: 1,
    visual_qc_validator_user: "undefined undefined (julie.coustenoble@imev-mer.fr)",
    visual_qc_status_id: 1,
    visual_qc_status_label: "PENDING",
    sample_type_id: 1,
    sample_type_label: "Time",
    project_id: 6
}
export const SearchSampleResult: { samples: PublicSampleModel[], search_info: SearchInfo } = {
    search_info: {
        total: 2,
        limit: 10,
        total_on_page: 2,
        page: 1,
        pages: 1
    },
    samples: [
        sampleModel_1,
        sampleModel_2
    ]
}
